services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: toni
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toni -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

  generator:
    build: ./generator
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  redash_postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: redash
      POSTGRES_USER: redash
      POSTGRES_PASSWORD: redash
    volumes:
      - redash_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  redash_server:
    image: redash/redash:latest
    depends_on:
      - redash_postgres
      - redis
    environment:
      REDASH_DATABASE_URL: postgres://redash:redash@redash_postgres:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_SECRET_KEY: key
    ports:
      - "5000:5000"
    command: server

  redash_worker:
    image: redash/redash:latest
    depends_on:
      - redash_server
    environment:
      REDASH_DATABASE_URL: postgres://redash:redash@redash_postgres:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_SECRET_KEY: key
    command: worker

  redash_scheduler:
    image: redash/redash:latest
    depends_on:
      - redash_server
    environment:
      REDASH_DATABASE_URL: postgres://redash:redash@redash_postgres:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_SECRET_KEY: key
    command: scheduler

volumes:
  pg_data:
  redash_pg_data: